# ln -s ~/.dotfiles/lazygit.config.yaml ~/Library/Application\ Support/lazygit/config.yml

gui:
  sidePanelWidth: 0.25
git: 
    paging:
        colorArg: always
        pager: delta --dark --paging=never --syntax-theme base16-256 -s
        externalDiffCommand: difft --color=always
